version: '2'
services:
  web:
    build: .
    environment:
     - MONGO_URL=mongodb://mongodb/kanban
    ports:
     - "3000:3000"
    volumes:
     - .:/code
     - /code/node_modules
  mongodb:
    image: "mongo:3.2"
